#ifndef SAMPLER_TYPES_H
#define SAMPLER_TYPES_H

#include <list>
#include <vector>

#include "Trajectory.h"

using namespace std;

namespace sampler {

	// A sample object generated by the sampler is a valid trajectory
	typedef Trajectory Sample;
	typedef list<Sample> Samples;

}

#endif
